name: Make Repo Public

on:
  schedule:
    - cron: '0 0 30 6 *'


jobs:
  change-visibility:
    runs-on: ubuntu-latest
    steps:
      - name: Make public via GitHub API
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/RaminMod/language-identifier \
            -d '{"private":false}'
